---
title: "07_Medium-PrestoBlue"
author: "Joris Van Meenen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Setup

## Load modules

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(ggprism)
library(ggforce)
library(rstatix)
library(emmeans)
library(tidyr)
library(scales)
library(ggstatsplot)
library(sandwich)
#library(nlme)

set.seed(42)
```

## Load data

```{r}
long <- data.frame()
startDate <- as.Date("20250824", format="%Y%m%d")
dir = "D://Documents//Work//Data//Cornea-on-chip//Epithelial barrier//07_Medium//Spark//"

xlsxList <- list.files(path = dir, pattern = "*.xlsx", full.names = TRUE, ignore.case = TRUE)

for (xlsx in xlsxList) {
  name <- basename(xlsx)
  raw <- read_xlsx(xlsx, col_names = FALSE)
  skip <- which(raw[[1]] == "<>")[1] - 1
  df <- read_xlsx(
    file.path(xlsx),
    skip = skip
  )
  df <- df[1:8,2:13]
  fluorescence <- as.vector(t(df))
  fluorescence <- fluorescence[!is.na(fluorescence) > 0]
  fluorescence<- as.numeric(fluorescence)
  if (name != "JVM_PrestoBlue (Modified)_20250825_172449.xlsx") {
    plate <- c(
      c(rep(1, 5), rep(3, 5)),
      c(rep(1, 5), rep(3, 5)),
      c(rep(1, 5), rep(NA, 5)),
      c(rep(1, 5), rep(NA, 5)),
      c(rep(1, 5), rep(2, 15))
    )
  
    condition <- c(
      rep(c("PBS", "HCE-T", "CnT-PR", "CnT-2D", "CnT-3D"), times = 5),
      rep("Reservoir", 5),
      c("PBS", "HCE-T", "CnT-PR", "CnT-2D", "CnT-3D"),
      rep("Reservoir", 5),
      rep(c("PBS", "HCE-T", "CnT-PR", "CnT-2D", "CnT-3D"), times = 4)
    )
  
    replicate <- c(
      c(rep(1, 5), rep(9, 5)),
      c(rep(2, 5), rep(10, 5)),
      c(rep(3, 5), 1:5),
      c(rep(4, 5), 6:10),
      rep(5:8, each = 5)
    )
  }
  else {
    plate <- c(
      c(rep(1, 5), rep(3, 5)),
      c(rep(1, 5), rep(3, 5)),
      c(rep(1, 5), rep(NA, 5)),
      c(rep(1, 5), rep(2, 20))
    )
  
    condition <- c(
      rep(c("PBS", "HCE-T", "CnT-PR", "CnT-2D", "CnT-3D"), times = 5),
      rep("Reservoir", 5),
      rep(c("PBS", "HCE-T", "CnT-PR", "CnT-2D", "CnT-3D"), times = 5)
    )
  
    replicate <- c(
      c(rep(1, 5), rep(9, 5)),
      c(rep(2, 5), rep(10, 5)),
      c(rep(3, 5), 1:5),
      rep(4:8, each = 5)
    )
  }

  
  df <- data.frame(
    "Plate" = plate,
    "Condition" = condition,
    "Replicate" = replicate,
    "Fluorescence (RFU)" = fluorescence, 
    check.names = FALSE
  )
  
  ## Add date and day variables
  date <- as.Date(strsplit(name, "_")[[1]][3], format="%Y%m%d")
  dateDiff <- as.double(date - startDate)
  df["Date"] <- rep(date, nrow(df))
  df["Days after seeding"] <- rep(dateDiff, nrow(df))

  long <- dplyr::bind_rows(long, df)
}

long$Condition <- factor(long$Condition, levels = c("PBS", "HCE-T", "CnT-PR", "CnT-2D", "CnT-3D", "Reservoir"))

long <- long %>%
  mutate(Group = case_when(
    Condition %in% c("Hydrogel control", "Control", "Reservoir") ~ "No cells",
    TRUE ~ "Cells"
  ))
```

## Outliers

```{r}
long <- long[long$`Days after seeding` > 1,]
```

## Visualisation

```{r, fig.width=12, fig.width=12}
dat <- long
x <- dat$`Days after seeding`
y <- dat$`Fluorescence (RFU)`

control_conditions <- c("Reservoir", "Control")
interesting_conditions <- setdiff(unique(dat$Condition), control_conditions)
dat_background <- dat %>%
  filter(Condition %in% interesting_conditions) %>%
  mutate(Condition_facet = Condition) %>%
  crossing(Condition_display = interesting_conditions) %>%
  filter(Condition_facet != Condition_display)
dat_interesting <- dat %>%
  filter(Condition %in% interesting_conditions) %>%
  mutate(Condition_display = Condition)
dat_control <- dat %>%
  filter(Condition %in% control_conditions) %>%
  crossing(Condition_display = interesting_conditions)
ggplot(data = dat, aes(x = `Days after seeding`, y = `Fluorescence (RFU)`)) + 
  geom_line(data = dat_background,
            aes(group = interaction(Condition_facet, Replicate)),
            color = "grey") +
  geom_point(data = dat_background,
            aes(group = interaction(Condition_facet, Replicate)),
            color = "grey", size = 2) +
  geom_line(data = dat_control,
            aes(color = Condition, 
            group = interaction(Condition, Replicate))
            ) +
  geom_point(data = dat_control,
            aes(color = Condition, 
            group = interaction(Condition, Replicate)), size = 2
            ) +
  geom_line(data = dat_interesting,
            aes(color = Condition, 
            group = interaction(Condition, Replicate))
            ) +
  geom_point(data = dat_interesting,
            aes(color = Condition, 
            group = interaction(Condition, Replicate)), size = 2
            ) +
  scale_y_continuous(limits = c(0, 55000), expand = c(0, 0)) +
  scale_x_continuous(limits = c(0, 16), expand = c(0, 0), guide = guide_prism_minor(), minor_breaks = seq(0, 16, 1)) +
  facet_wrap(~ factor(Condition_display, levels = c("HCE-T", "CnT-PR", "CnT-2D", "CnT-3D", "PBS", "Reservoir")), scales = "free") +
  scale_color_manual(
    breaks = c("HCE-T", "CnT-PR", "CnT-2D", "CnT-3D", "PBS", "Reservoir", "Measurement medium"),
    values = c("HCE-T" = "#F8766D", "CnT-PR" = "#DB8E00", "CnT-2D" = "#AEA200", "CnT-3D" = "#64B200", "PBS" = "#00BD5C", "Reservoir" = "#00C1A7", "Measurement medium" = "#00BADE")) +
    theme_prism(base_size = 22, base_line_size = 1.2) +
    theme(panel.spacing.x = unit(1.5, "lines"), legend.key.spacing.y = unit(0.5, "lines"))
```

# Before vs after

## Normalisation

```{r}
normalised <- long %>%
  mutate( 
    `Normalised Fluorescence (AU)` = `Fluorescence (RFU)` / mean(`Fluorescence (RFU)`[Group == "No cells"]),
  ) %>%
  filter(Group != "No cells")
```

## Statistics

```{r}
dat <- droplevels(normalised[normalised$`Days after seeding` == 8 | normalised$`Days after seeding` == 15,])
dat$`Days after seeding` <- factor(dat$`Days after seeding`, levels = c(8, 15), labels = c("Before", "After"))
renamed_dat <- dat %>%
  rename(Fluorescence = `Normalised Fluorescence (AU)`) %>%
  rename(Time = `Days after seeding`)

model <- lm(Fluorescence ~ Time * Condition, data = renamed_dat)

## Normality
ggqqplot(data = residuals(model), 
         ggtheme = theme_prism()
         )
ggqqplot(data = dat,
         x = "`Normalised Fluorescence (AU)`",
         facet.by = c("Days after seeding", "Condition"),
         ggtheme = theme_prism()
         )

shapiro_test(residuals(model))
shapiro_individual <- renamed_dat %>%
  group_by(Time, Condition) %>%
  shapiro_test(Fluorescence)

## Homogeneity of variances
plot(model, 1)
dat %>% 
  levene_test(`Normalised Fluorescence (AU)` ~ `Days after seeding` * Condition)
dat_summary <- dat %>%
  group_by(`Days after seeding`, Condition) %>%
  get_summary_stats(`Normalised Fluorescence (AU)`, type = "mean_sd")
max(dat_summary$sd)/min(dat_summary$sd)

## ANOVA
anova_results <- Anova(model, type = 3, white.adjust = "hc3")
print(anova_results)

## Pairwise
emm_options(parens = "a^")
vcovHC3 <- vcovHC(model, type = "HC3")
emm_Resistance <- emmeans(model, ~ Time * Condition, vcov. = vcovHC3)
pairs(emm_Resistance, by = "Condition", adjust = "bonferroni")
stat_Resistance <- summary(pairs(emm_Resistance, by = "Condition", adjust = "bonferroni")) %>%
  separate(contrast, into = c("group1", "group2"),
           sep = " - ") %>%
  rename(p.adj = p.value) %>%
  add_significance("p.adj")
stat_Resistance_pos <- stat_Resistance %>%
  add_xy_position(
    x = "Time",
    data = renamed_dat,
    formula = Fluorescence ~ Time,
  ) %>%
  mutate(
    xmin = match(group1, levels(renamed_dat$Time)),
    xmax = match(group2, levels(renamed_dat$Time)),
  ) %>% 
  group_by(Condition) %>%
  mutate(
    y.position = max(renamed_dat$Fluorescence[renamed_dat$Condition == unique(Condition)]) + (row_number() * max(renamed_dat$Fluorescence[renamed_dat$Condition == unique(Condition)])/5)
    ) %>%
  ungroup()
```

## Visualisation

```{r}
dat <- droplevels(normalised[normalised$`Days after seeding` == 8 | normalised$`Days after seeding` == 15,])
dat$`Days after seeding` <- factor(dat$`Days after seeding`, levels = c(8, 15), labels = c("Before", "After"))
y <- dat$`Normalised Fluorescence (AU)`

ggplot(data = dat, aes(x = `Days after seeding`, y = y, color = Condition)) + 
  geom_violin(width = 0.5, scale = "width", alpha = 0.2, colour = "black", linewidth = 1) +
  geom_sina(size = 4, maxwidth = 0.5, scale = FALSE, alpha =
    0.4, stroke = 0) +
  coord_cartesian(clip = "off") +
  stat_summary(geom = "point", fun = "mean", size = 0.5, shape = 3, colour = "black", stroke = 1.5) +
  stat_summary(geom = "errorbar", fun.data = "mean_sdl", fun.args = list(mult = 1), width = 0.2, colour = "black", linewidth = 1) +
  ylab(names(which(sapply(dat, identical, y = y)))) +
  scale_y_continuous(limits = c(0, 20), expand = c(0, 0), oob = oob_keep, guide = guide_prism_minor()) +
  stat_pvalue_manual(
    stat_Resistance_pos,
    label = "p.adj.signif",
    tip.length = 0.025,
    size = 7.76,
    linewidth = 1,
  ) +
  geom_hline(yintercept = 1, linetype="dashed") +
  scale_color_manual(
    breaks = c("HCE-T", "CnT-PR", "CnT-2D", "CnT-3D", "PBS", "Reservoir", "Measurement medium"),
    values = c("HCE-T" = "#F8766D", "CnT-PR" = "#DB8E00", "CnT-2D" = "#AEA200", "CnT-3D" = "#64B200", "PBS" = "#00BD5C", "Reservoir" = "#00C1A7", "Measurement medium" = "#00BADE")) +
    facet_wrap(~ factor(Condition, levels = c("HCE-T", "CnT-PR", "CnT-2D", "CnT-3D", "PBS")), scales = "free") +
    theme_prism(base_size = 28) +
    theme(plot.margin = margin(t = 50, b = 20, unit = "pt"), legend.key.spacing.y = unit(0.5, "lines"))


```

# Extra

```{r}
renamed_dat <- dat %>%
  rename(Fluorescence = `Fluorescence (RFU)`)

model <- lm(`Normalised Fluorescence (AU)` ~ Condition, data = dat)

## Normality
ggqqplot(data = residuals(model), 
         ggtheme = theme_prism()
         )
ggqqplot(data = dat,
         x = "`Normalised Fluorescence (AU)`",
         facet.by = "Condition",
         ggtheme = theme_prism()
         )

shapiro_test(residuals(model))
renamed_dat %>%
  group_by(Condition) %>%
  shapiro_test(Fluorescence)

## Homogeneity of variances
plot(model, 1)
dat %>% 
  levene_test(`Normalised Fluorescence (AU)` ~ Condition)
dat_summary <- dat %>%
  group_by(Condition) %>%
  get_summary_stats(`Fluorescence (RFU)`, type = "mean_sd")
max(dat_summary$sd)/min(dat_summary$sd)

## ANOVA
anova_results <- Anova(model, type = 2, white.adjust = "hc3")
print(anova_results)

## Pairwise
emm_options(parens = "a^")
vcovHC3 <- vcovHC(model, type = "HC3")
emm_cell <- emmeans(model, ~ Condition, vcov. = vcovHC3)
pairs(emm_cell, adjust = "bonferroni")
stat_cell <- summary(pairs(emm_cell, adjust = "bonferroni")) %>%
  separate(contrast, into = c("group1", "group2"),
           sep = " - ") %>%
  rename(p.adj = p.value) %>%
  add_significance("p.adj")
stat_cell_pos <- stat_cell %>%
  add_xy_position(
    x = "Condition",
    data = dat,
    formula = `Normalised Fluorescence (AU)` ~ Condition,
  ) %>%
  mutate(y.position = 6.6 + (row_number() * 0.5)) %>%
  mutate(
    xmin = match(group1, levels(droplevels(dat$Condition))),
    xmax = match(group2, levels(droplevels(dat$Condition))),
  )
```
